# Generated by Django 3.2.8 on 2021-10-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
    ]
