# Generated by Django 3.2.8 on 2021-10-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_bio_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.TextField(default=False, max_length=200, null=True),
        ),
    ]
