# Generated by Django 3.2.8 on 2021-10-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dataOfPosted',
            new_name='dateOfPosted',
        ),
    ]
